# Reusable workflow for license compliance
name: License Compliance

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: '.NET SDK version'
        required: false
        type: string
        default: '8.0.x'

jobs:
  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Generate package list (JSON format)
      run: |
        mkdir -p ./licenses
        echo "Generating package information..."
        dotnet list package --include-transitive --format json > ./licenses/packages.json || echo "{}" > ./licenses/packages.json
      continue-on-error: true
    
    - name: Generate license report (Markdown)
      run: |
        echo "# License Compliance Report" > ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> ./licenses/LICENSE-REPORT.md
        echo "**Repository:** ${{ github.repository }}" >> ./licenses/LICENSE-REPORT.md
        echo "**Commit:** ${{ github.sha }}" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "---" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "## NuGet Package Dependencies" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        dotnet list package --include-transitive >> ./licenses/LICENSE-REPORT.md || echo "Error generating package list" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "---" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "## Project Files Scanned" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        find . -name "*.csproj" -type f >> ./licenses/LICENSE-REPORT.md || echo "No project files found" >> ./licenses/LICENSE-REPORT.md
      continue-on-error: true
    
    - name: Check for packages with known restrictive licenses
      run: |
        echo "Checking for packages with restrictive licenses..."
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "---" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "## License Check Summary" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        
        if grep -i "gpl\|lgpl\|agpl\|copyleft" ./licenses/packages.json 2>/dev/null; then
          echo "⚠️ **WARNING:** Potentially restrictive licenses detected. Please review manually." >> ./licenses/LICENSE-REPORT.md
          echo "⚠️ Found potentially restrictive licenses"
        else
          echo "✅ **INFO:** No obviously restrictive licenses detected in package metadata." >> ./licenses/LICENSE-REPORT.md
          echo "✅ No obvious restrictive licenses found"
        fi
        
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "> **Note:** This is a basic automated check. Manual review is recommended for production use." >> ./licenses/LICENSE-REPORT.md
        echo "> For detailed license information, visit the NuGet package pages or use a dedicated license scanning tool." >> ./licenses/LICENSE-REPORT.md
      continue-on-error: true
    
    - name: Generate compliance summary
      run: |
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "---" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "## Compliance Actions" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "- [ ] Review all package licenses" >> ./licenses/LICENSE-REPORT.md
        echo "- [ ] Verify compatibility with project license" >> ./licenses/LICENSE-REPORT.md
        echo "- [ ] Document any license exceptions" >> ./licenses/LICENSE-REPORT.md
        echo "- [ ] Update NOTICE file if required" >> ./licenses/LICENSE-REPORT.md
        echo "" >> ./licenses/LICENSE-REPORT.md
        echo "For detailed license texts, visit:" >> ./licenses/LICENSE-REPORT.md
        echo "- NuGet Package Pages: https://www.nuget.org/packages/" >> ./licenses/LICENSE-REPORT.md
        echo "- License Information: Check individual package pages" >> ./licenses/LICENSE-REPORT.md
    
    - name: Upload license report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: license-report
        path: ./licenses
